### ISSUE TITLE
刷新存在bug,容易出现刷新之后还在的问题

### ISSUE THREAD

**Issue by lozn00** [29995270/HorizontalRefreshLayout#1]
跪求解决。

**Comment by 29995270** [comment]
尝试使用 post 调用 onRefreshComplete()  ，看看是不是线程问题 @qssq

**Comment by lozn00** [comment]
我是在主线程操作的,不存在，我之后修复了，吧一个动画代码删除了就好了，那个动画代码好像是多余的。
